development: &default
  adapter: postgresql
  database: railsgirls_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: railsgirls_test
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
